### ISSUE TITLE
The speakers view is broken

### ISSUE THREAD

**Issue by ueman** [TheFlutteristas/flutteristas_website#16]
When I open the speakers page, I see the following content:

![Screenshot_20231024-165036~2](https://github.com/TheFlutteristas/flutteristas_website/assets/1270149/fe66dafb-18e3-4480-b861-077fd0e16a3a)

**Comment by Stef-GMS** [comment]
Thank you @ueman for letting us know.

**Comment by Stef-GMS** [comment]
This issue has been fixed with PR #17
