### ISSUE TITLE
The icon of kodeco is not loading

### ISSUE THREAD

**Issue by esrakadah** [TheFlutteristas/flutteristas_website#19]
1 - Can we double-check the asset? It is functionally working.
2- Widgetbook is also written as 'Widgetbook' so, no we can use 'lower case' in the 'book' word in their name.

<img width="1124" alt="Screenshot 2023-10-26 at 16 12 59" src="https://github.com/TheFlutteristas/flutteristas_website/assets/87121319/56b8e2f2-5231-4bad-8dc1-f2f5c0401d88">

**Comment by Farahkh** [comment]
fixed
