### ISSUE TITLE
Page Frame doesn't fill browser

### ISSUE THREAD

**Issue by Stef-GMS** [TheFlutteristas/flutteristas_website#2]
The page frame isn't filling the browser. There is grey space to the right.

<img width="1695" alt="image" src="https://github.com/TheFlutteristas/flutteristas_website/assets/10969726/669d200a-b822-40c0-bb25-a9ea60c2c214">

**Comment by Beelzenef** [comment]
Other tabs looks better, but still the same problem:

![image](https://github.com/TheFlutteristas/flutteristas_website/assets/6389665/8d3de49b-c521-490d-b435-0bff37129876)

**Comment by Stef-GMS** [comment]
The fix is part of [this PR](https://github.com/TheFlutteristas/flutteristas_website/pull/6).

**Comment by Stef-GMS** [comment]
This has been fixed.
